### ISSUE TITLE
Cannot import package[Bug]

### ISSUE THREAD

**Issue by chiwwong** [quentinblampey/spatialdata_xenium_explorer#6]
## Description
The package cannot be imported

## Reproducing the issue
I ran the following codes according to he tutorial:
```
from spatialdata_io.readers.xenium import xenium_aligned_image
from pathlib import Path
```

## Expected behavior
I saw the following error:

> ---------------------------------------------------------------------------
> ImportError                               Traceback (most recent call last)
> Cell In[6], line 1
> ----> 1 from spatialdata_io.readers.xenium import xenium_aligned_image
>       2 from pathlib import Path
> 
> File /miniconda3/envs/xenium-publication-env/lib/python3.10/site-packages/spatialdata_io/readers/xenium.py:32
>      30 from spatial_image import SpatialImage
>      31 from spatialdata import SpatialData
> ---> 32 from spatialdata._core.query.relational_query import _get_unique_label_values_as_index
>      33 from spatialdata._types import ArrayLike
>      34 from spatialdata.models import (
>      35     Image2DModel,
>      36     Labels2DModel,
>    (...)
>      39     TableModel,
>      40 )
> 
> ImportError: cannot import name '_get_unique_label_values_as_index' from 'spatialdata._core.query.relational_query' (/miniconda3/envs/xenium-publication-env/lib/python3.10/site-packages/spatialdata/_core/query/relational_query.py)

## System
 - OS: [e.g. Linux]
 - Python version [e.g. 3.10.13]
<details>
<summary>Dependencies versions</summary>
<br>
Package                     Version
--------------------------- --------------
aiobotocore                 2.5.4
aiohttp                     3.9.5
aioitertools                0.11.0
aiosignal                   1.3.1
anndata                     0.10.7
annotated-types             0.6.0
anyio                       4.3.0
argon2-cffi                 23.1.0
argon2-cffi-bindings        21.2.0
array_api_compat            1.6
arrow                       1.3.0
asciitree                   0.3.3
asttokens                   2.4.1
async-lru                   2.0.4
async-timeout               4.0.3
attrs                       23.2.0
Babel                       2.14.0
backcall                    0.2.0
beautifulsoup4              4.12.3
bleach                      6.1.0
botocore                    1.31.17
certifi                     2024.2.2
cffi                        1.16.0
charset-normalizer          3.3.2
click                       8.1.7
click-plugins               1.1.1
cligj                       0.7.2
cloudpickle                 3.0.0
colorcet                    3.1.0
comm                        0.1.4
contourpy                   1.2.1
cramjam                     2.7.0
cycler                      0.12.1
dask                        2024.2.1
dask-image                  2023.8.1
datashader                  0.16.1
debugpy                     1.8.0
decorator                   5.1.1
defusedxml                  0.7.1
distributed                 2024.2.1
exceptiongroup              1.2.1
executing                   2.0.0
fasteners                   0.19
fastjsonschema              2.19.1
fastparquet                 2023.10.1
fcsparser                   0.2.8
fiona                       1.9.6
fonttools                   4.51.0
fqdn                        1.5.1
frozenlist                  1.4.1
fsspec                      2023.6.0
geopandas                   0.14.3
h11                         0.14.0
h5py                        3.11.0
httpcore                    1.0.5
httpx                       0.27.0
idna                        3.7
imagecodecs                 2024.1.1
imageio                     2.34.0
importlib_metadata          7.1.0
ipykernel                   6.26.0
ipython                     8.16.1
isoduration                 20.11.0
jedi                        0.19.1
Jinja2                      3.1.3
jmespath                    1.0.1
joblib                      1.4.0
json5                       0.9.25
jsonpointer                 2.4
jsonschema                  4.21.1
jsonschema-specifications   2023.12.1
jupyter_client              8.5.0
jupyter_core                5.4.0
jupyter-events              0.10.0
jupyter-lsp                 2.2.5
jupyter_server              2.14.0
jupyter_server_terminals    0.5.3
jupyterlab                  4.1.6
jupyterlab_pygments         0.3.0
jupyterlab_server           2.26.0
kiwisolver                  1.4.5
lamin_utils                 0.13.2
lazy_loader                 0.4
legacy-api-wrap             1.4
llvmlite                    0.42.0
locket                      1.0.0
markdown-it-py              3.0.0
MarkupSafe                  2.1.5
matplotlib                  3.8.4
matplotlib-inline           0.1.6
mdurl                       0.1.2
mistune                     3.0.2
msgpack                     1.0.8
multidict                   6.0.5
multipledispatch            1.0.0
multiscale_spatial_image    0.11.2
natsort                     8.4.0
nbclient                    0.10.0
nbconvert                   7.16.3
nbformat                    5.10.4
nest-asyncio                1.5.8
networkx                    3.3
notebook_shim               0.2.4
numba                       0.59.1
numcodecs                   0.12.1
numpy                       1.23.4
ome-types                   0.4.2
ome-zarr                    0.8.3
opencv-python               4.8.1.78
overrides                   7.7.0
packaging                   24.0
pandas                      2.2.2
pandocfilters               1.5.1
param                       2.1.0
parso                       0.8.3
partd                       1.4.1
patsy                       0.5.6
pexpect                     4.8.0
pickleshare                 0.7.5
pillow                      10.3.0
PIMS                        0.6.1
pip                         23.3.2
platformdirs                4.2.0
pooch                       1.8.1
prometheus_client           0.20.0
prompt-toolkit              3.0.39
psutil                      5.9.8
ptyprocess                  0.7.0
pure-eval                   0.2.2
pyarrow                     16.0.0
pycparser                   2.22
pyct                        0.5.0
pydantic                    2.4.2
pydantic_core               2.10.1
pygeos                      0.14
Pygments                    2.17.2
pynndescent                 0.5.12
pyparsing                   3.1.2
pyproj                      3.6.1
python-dateutil             2.9.0.post0
python-json-logger          2.0.7
pytz                        2024.1
PyYAML                      6.0.1
pyzmq                       25.1.1
readfcs                     1.1.8
referencing                 0.34.0
requests                    2.31.0
rfc3339-validator           0.1.4
rfc3986-validator           0.1.1
rich                        13.7.1
rpds-py                     0.18.0
s3fs                        2023.6.0
scanpy                      1.10.1
scikit-image                0.23.2
scikit-learn                1.4.2
scipy                       1.13.0
seaborn                     0.13.2
Send2Trash                  1.8.3
session_info                1.0.0
setuptools                  69.5.1
shapely                     2.0.4
six                         1.16.0
slicerator                  1.1.0
sniffio                     1.3.1
sortedcontainers            2.4.0
soupsieve                   2.5
spatial_image               0.3.0
spatialdata                 0.1.2
spatialdata-io              0.1.2
spatialdata_xenium_explorer 0.1.6
stack-data                  0.6.3
statsmodels                 0.14.2
stdlib-list                 0.10.0
tbb                         2021.10.0
tblib                       3.0.0
terminado                   0.18.1
threadpoolctl               3.4.0
tifffile                    2024.4.18
tinycss2                    1.2.1
tomli                       2.0.1
toolz                       0.12.1
tornado                     6.4
tqdm                        4.66.2
traitlets                   5.12.0
typer                       0.9.4
types-python-dateutil       2.9.0.20240316
typing_extensions           4.11.0
tzdata                      2024.1
umap-learn                  0.5.6
uri-template                1.3.0
urllib3                     1.26.18
wcwidth                     0.2.8
webcolors                   1.13
webencodings                0.5.1
websocket-client            1.7.0
wheel                       0.43.0
wrapt                       1.16.0
xarray                      2023.12.0
xarray-dataclasses          1.7.0
xarray-datatree             0.0.14
xarray-schema               0.0.3
xarray-spatial              0.3.7
xsdata                      23.8
yarl                        1.9.4
zarr                        2.17.2
zict                        3.0.0
zipp                        3.18.1
</details>

**Comment by quentinblampey** [comment]
Hello @chiwwong,

Thanks for reporting this issue! I released a new version where this should be fixed. Can you try to upgrade to `spatialdata_xenium_explorer==0.1.7` and `spatialdata-io>=0.1.2`?

Some important changes in `spatialdata` caused these issues, but now `spatialdata` is stable and will always be retro-compatible. Therefore, `spatialdata_xenium_explorer` should also soon be stable.
I'll also probably update/improve the tutorial and add it to the [Sopa tutorials](https://gustaveroussy.github.io/sopa/).

**Comment by quentinblampey** [comment]
Closing, as `spatialdata_xenium_explorer` is not maintained anymore. Refer to [sopa](https://github.com/gustaveroussy/sopa) instead.
